### ISSUE TITLE
UI tweaks: user should see offer before hitting Make Offer, etc.

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-offer-up#17]
1. As a User, when the dapp loads up the page, it should show images of the 3 items / with images / and prices

- Update the Dapp with 3 images with the actual image of the item for sale e.g. an NFT and a Virtual Land.
- Label them ("Items listed on OfferUp")

- Add 1 total price for all the items so its clear what is the offer I need to make

Reasoning - Currently the user doesn't see the offer until AFTER they click on "Make Offer" and the offer shows up in the wallet. This should be shown on the dapp itself.

2. As a User, I should be shown whats in my purse and what I own

-  "Places" show none. Its not clear if these are my places that I own. 

- Rename to "Places I own" or "My Collectible items"

- Instead of "IST", label it "My Wallet (IST)"

3. The button "Make Offer" -> change label to "Make an Offer"

**Comment by dckc** [comment]
should be assigned to @kbennett2000

**Comment by sufyaankhan** [comment]
1. As a User, when the dapp loads up the page, it should show images of the 3 items / with images / and prices

- Update the Dapp with 3 images with the actual image of the item for sale e.g. an NFT and a Virtual Land.
- Label them ("Items listed on OfferUp")

- Add 1 total price for all the items so its clear what is the offer I need to make

Reasoning - Currently the user doesn't see the offer until AFTER they click on "Make Offer" and the offer shows up in the wallet. This should be shown on the dapp itself.

2. As a User, I should be shown whats in my purse and what I own

-  "Places" show none. Its not clear if these are my places that I own. 

- Rename to "Places I own" or "My Collectible items"

- Instead of "IST", label it "My Wallet (IST)"

3. The button "Make Offer" -> change label to "Make an Offer"

**Comment by dckc** [comment]
icons for places:

 - Mordor: [Evil tower icon, SVG and PNG \| Game\-icons\.net](https://game-icons.net/1x1/delapouite/evil-tower.html)
 - Misty Mountains: [Mountains icon, SVG and PNG \| Game\-icons\.net](https://game-icons.net/1x1/lorc/mountains.html)
 - Shire: [Hobbit dwelling icon, SVG and PNG \| Game\-icons\.net](https://game-icons.net/1x1/delapouite/hobbit-dwelling.html)
